version: '3'
services:
  redis:
    container_name: chat-server-redis
    image: redis
    networks:
      portfolio-server_portfolio:
        aliases:
          - redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis/data/
  node:
    container_name: portfolio-chat-server
    networks:
      portfolio-server_portfolio:
        aliases:
          - portfolio-chat-server-service
    depends_on:
      - redis
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile

networks:
  portfolio-server_portfolio:
    external: true

volumes:
  redis-data:
