FROM node:14.16-alpine
ARG REDIS_HOST
ARG ADMIN_USER_ID
ARG ADMIN_PASSWORD
ARG ADMIN_SESSION_ID
ARG ADMIN_USER_NAME
ENV ADMIN_PASSWORD=${ADMIN_PASSWORD} ADMIN_USER_ID=${ADMIN_USER_ID} ADMIN_SESSION_ID=${ADMIN_SESSION_ID} ADMIN_USER_NAME=${ADMIN_USER_NAME} REDIS_HOST=${REDIS_HOST}

WORKDIR /usr/src/app/

COPY src src/
COPY package.json yarn.lock .env tsconfig.json ./

RUN yarn
RUN yarn build

EXPOSE 9000 9001

CMD ["node", "."]
