apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: portfolio-chat-server-autoscaler
  namespace: portfolio
  labels:
    app: portfolio-chat-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: portfolio-chat-server
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
