apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: portfolio-chat-server-autoscaler
  namespace: portfolio
  labels:
    app: portfolio-chat-server
spec:
  scaleTargetRef:
    kind: Deployment
    name: portfolio-chat-server
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
