apiVersion: v1
kind: Service
metadata:
  name: portfolio-chat-service
  namespace: portfolio
  labels:
    app: portfolio-chat-server
spec:
  type: NodePort
  selector:
    app: portfolio-chat-server
  ports:
    - port: 9000
      targetPort: 9000
